# About Dataset

**Context**  
This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

**Content**  
5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014.  
Contains total of 982,619 entries.  
Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.  

**Columns:**
- `asin` - ID of the product, like B000FA64PK
- `helpful` - helpfulness rating of the review – example: 2/3.
- `overall` - rating of the product.
- `reviewText` - text of the review (heading).
- `reviewTime` - time of the review (raw).
- `reviewerID` - ID of the reviewer, like A3SPTOKDG7WBLN
- `reviewerName` - name of the reviewer.
- `summary` - summary of the review (description).
- `unixReviewTime` - unix timestamp.

**Acknowledgements**  
This dataset is taken from Amazon product data, Julian McAuley, UCSD website.  
[http://jmcauley.ucsd.edu/data/amazon/](http://jmcauley.ucsd.edu/data/amazon/)

**License**  
License to the data files belong to them.

**Inspiration**
- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review / What factors influence helpfulness of a review.
- Fake reviews / outliers.
- Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
- Any other interesting analysis.


#### best practices to learn in this project  
1. Preprocessing and cleaning
2. Train Test split
3. BOW,TF-IDF,Word2vec
4.Train Ml Algorithm

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns



In [2]:
data=pd.read_csv('all_kindle_review.csv')
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [3]:
data=data[['reviewText','rating']]

In [4]:
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [5]:
data.shape

(12000, 2)

In [6]:
## Missing Values
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [7]:
data['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [8]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [9]:
## Preprocessing and Cleaning

#Lets solve this case in such as way that 
#ratings <=3 are considered as negative review
#ratings >3 are considered as positive review

## Postive review is 1 and negative review is 0
data['rating']=data['rating'].apply(lambda x:0 if x<3 else 1) 

In [10]:
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [11]:
data['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [12]:
## 1. Lower all the cases
data['reviewText']=data['reviewText'].str.lower()

In [13]:
data.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

Imporatnt Things to consider while cleaning Corpus

1)Convert to lowercase

text = text.lower()

2)Remove URLs, emails, and mentions (@username)

text = re.sub(r'http\S+|www\S+|@\S+', '',text)

3)Remove punctuation and special characters

text = re.sub(r'[^\w\s]', '', text)

4)Remove numbers

text = re.sub(r'\d+', '', text)

5)Remove extra whitespaces

text = ' '.join(text.split())

In [14]:
#Lower all the cases 
data["reviewText"]=data["reviewText"].str.lower()

In [15]:
data.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [16]:
!pip install bs4 
import re 
from bs4 import BeautifulSoup
import nltk 
from nltk.corpus import stopwords

In [17]:
data.head(5)

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [18]:
# Removing special characters 
data["reviewText"]=data['reviewText'].apply(lambda x:re.sub('[^a-zA-Z0-9]+',' ',x))

In [19]:
data.head(5)

reviewText  rating
0  jace rankin may be short but he s nothing to m...       1
1  great short read i didn t want to put it down ...       1
2  i ll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [20]:
# Removing stop words
data["reviewText"]=data["reviewText"].apply(lambda x:" ".join([y for y in x.split() if y not in set(stopwords.words("english"))]))


In [21]:
 # Remove URLs, emails, and mentions (@username)
data["reviewText"]=data["reviewText"].apply(lambda x:re.sub(r'http\S+|www\S+|@\S+', ' ',x))

In [22]:
data.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four books expecting 34 con...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [23]:
import numpy as np 
import sys  
np.set_printoptions(threshold=sys.maxsize)
print(data["reviewText"])

0        jace rankin may short nothing mess man hauled ...
1        great short read want put read one sitting sex...
2        start saying first four books expecting 34 con...
3        aggie angela lansbury carries pocketbooks inst...
4        expect type book library pleased find price right
                               ...                        
11995    valentine cupid vampire jena ian another vampi...
11996    read seven books series apocalyptic adventure ...
11997    book really cuppa situation man capturing woma...
11998    tried use charge kindle even register charging...
11999    taking instruction look often hidden world sex...
Name: reviewText, Length: 12000, dtype: object


In [24]:
#for removing extra spaces
data["reviewText"]=data["reviewText"].apply(lambda x: " ".join(x.split()))

In [25]:
data.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four books expecting 34 con...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [26]:
## lemmatizer 
from nltk.stem import WordNetLemmatizer
lemmatize=WordNetLemmatizer()

In [27]:
def lemmatize_words(text):
    return " ".join([lemmatize.lemmatize(word) for word in text.split()])

In [28]:
data['reviewText']=data['reviewText'].apply(lambda x:lemmatize_words(x))

In [29]:
data.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four book expecting 34 conc...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [30]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    data['reviewText'],
    data['rating'],
    test_size=0.20
)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=CountVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [33]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB()
nb_model_bow.fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB()
nb_model_tfidf.fit(X_train_tfidf,y_train)


GaussianNB()

In [34]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [35]:
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_tfidf.predict(X_test_tfidf)

In [36]:
print("Bow accuracy",accuracy_score(y_test,y_pred_bow))

Bow accuracy 0.575


In [38]:
cm=confusion_matrix(y_test,y_pred_bow)
cm

array([[516, 290],
       [730, 864]], dtype=int64)

In [39]:
print("tfidf accuracy",accuracy_score(y_test,y_pred_tfidf))

tfidf accuracy 0.575


In [41]:
cm=confusion_matrix(y_test,y_pred_tfidf)
cm

array([[516, 290],
       [730, 864]], dtype=int64)

In [42]:
## To get the more accuracy we want use the word2vec